title: Heating Process Optimization in Thermoforming trough Surrogate Modeling and Artificial Neural Network(ANN)
description: null
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman


#title: Heating Process Optimization in Thermoforming trough Surrogate Modeling and Artificial Neural Network(ANN)
#theme: jekyll-theme-cayman

github:
  is_project_page: false
