remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Heating Process Optimization in Thermoforming trough Surrogate Modeling and Artificial Neural Network(ANN)]
description: [Below you can see the results obtained for the validation dataset regarding the Surrogate Model and the Inverse Model. Lastly, the result of a real-world use case for Gradient Descent optimization are reported]

github:
  is_project_page: false
